require('dotenv').config();

module.exports = {
    VOICE_CHANNEL_ID: process.env.VOICE_CHANNEL_ID || 'YAPI_BEKLEYEN_SES_KANAL_ID',
    TARGET_ROLE_ID: process.env.TARGET_ROLE_ID || 'KAYITSIZ_ROL_ID',
    STAFF_ROLE_ID: process.env.STAFF_ROLE_ID || 'YETKILI_ROL_ID',
    REGISTERED_ROLE_ID: process.env.REGISTERED_ROLE_ID || 'KAYITLI_ROL_ID',
    STAFF_NOTIFICATION_CHANNEL_ID: process.env.STAFF_NOTIFICATION_CHANNEL_ID || 'YETKILI_METIN_KANAL_ID',
    WELCOME_TEXT_CHANNEL_ID: process.env.WELCOME_TEXT_CHANNEL_ID || 'KARSI_METIN_KANAL_ID',
    ENABLED: true,
    VOLUME: 0.8,
    AUTO_LEAVE: true,
    LEAVE_DELAY: 5000
};
